### PR TITLE
Clean up, code style, formatting.

### PR DESCRIPTION
**Pull request by jonkemp**
Add support for JSHint, .editorconfig. 

Clean up formatting. Make code style consistent. Fix lint error.

### CODE REVIEW

**Comment by jonkemp** [comment]
Can we discuss? Is this wanted or not?

**Comment by manuelcabral** [comment]
I'm afraid this project is no longer being maintained. We encourage you to fork it if it is useful.

**Comment by jonkemp** [comment]
I can fork it yes, but can you make me a contributor or transfer ownership to me? My gulp plugin depends on it and it got over 20,000 downloads last week according to npm so it's pretty widely used.

**Comment by manuelcabral** [comment]
I'm afraid I can't. But I will be happy to refer to your fork on the deprecation notice.

**Comment by jonkemp** [comment]
Ok thanks. Here's my fork then.

https://github.com/jonkemp/useref

**Pull request closed without merging**
